### ISSUE TITLE
[BUG] -unable to deploy

### ISSUE THREAD

**Issue by PSSENT** [aws-samples/terraform-aws-windows-workloads-on-aws#3]
Unable to deploy in isegard (us-east-1, us-west-2 ) or workshop studio.

https://github.com/aws-samples/terraform-aws-windows-workloads-on-aws/blob/main/workshops/ENT303/pdo_cfn.yaml

Resource handler returned message: “The role with name pdoiarpdcloud9admin01 cannot be found. (Service: Iam, Status Code: 404, Request ID: )” (RequestToken: , HandlerErrorCode: NotFound)

**Comment by marciogmorales** [comment]
PR merged.
