### ISSUE TITLE
[BUG] Two tunnels do not get BGP Routes for module aws-to-azure-bgp-vpn

### ISSUE THREAD

**Issue by DevopsMercenary** [aws-samples/terraform-aws-windows-workloads-on-aws#5]
## Description

I deployed the module `aws-to-azure-bgp-vpn` but two of the tunnels do not get any routes

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

I cloned the repo directly from github and used the main branch

'Latest' which I suppose is 1.1.7 

- Terraform version:
```
Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.30.0
+ provider registry.terraform.io/hashicorp/azuread v2.46.0
+ provider registry.terraform.io/hashicorp/azurerm v3.84.0
```
- Provider version(s):
```
Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.30.0
+ provider registry.terraform.io/hashicorp/azuread v2.46.0
+ provider registry.terraform.io/hashicorp/azurerm v3.84.0
```
## Reproduction Code [Required]

I cloned out the main branch directly from github.

and I added two files to the root of the project

`provider.tf`
```
provider "azuread" {
}

provider "azurerm" {
  features {}
}
```

`module.tf`
```
module "aws-to-azure-bgp-vpn" {
  source = "./modules/aws-to-azure-bgp-vpn"

  aws_location   = "us-west-2"
  azure_location = "eastus"
}
```

`terraform apply`

## Expected behavior

It's my understanding that all 4 tunnels will receive the BGP routes.

## Actual behavior

My Azure VNG Gateway

![image](https://github.com/aws-samples/terraform-aws-windows-workloads-on-aws/assets/112259176/652c9213-d8c3-487b-a79c-cd1196b2a026)

AWS Tunnels

![image](https://github.com/aws-samples/terraform-aws-windows-workloads-on-aws/assets/112259176/bffe8e6f-f07f-4825-8f7b-064b20daf13e)

![image](https://github.com/aws-samples/terraform-aws-windows-workloads-on-aws/assets/112259176/6d3e85dd-e6f1-400d-923b-1f0aa06c88e5)

### Terminal Output Screenshot(s)

There's no error

**Comment by marciogmorales** [comment]
Hello,
I assigned @irlperu as he is the the module author.

**Comment by ajkeane-aws** [comment]
The architectural differences between Azure and AWS VPN services stem from their distinct design approaches. In an active-active VPN configuration, Azure exposes two public IP addresses which requires the configuration in AWS to use two customer gateways. This leads to setting up two VPN connections in AWS, each with two tunnels by default. In our case, while connecting to Azure, the second tunnel in each AWS connection is not utilized, but it's brought online to avoid warning messages from AWS.  We activate these redundant tunnels only to suppress AWS's warning messages, not for actual data transmission.

For further technical guidance, please see the AWS documentation on redundant VPN connections 

[Using redundant Site-to-Site VPN connections to provide failover](https://docs.aws.amazon.com/vpn/latest/s2svpn/vpn-redundant-connection.html)

Microsoft's documentation on BGP and active-active VPN gateways 

[How to connect AWS and Azure using a BGP-enabled VPN gateway](https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-aws-bgp) 
[Highly Available cross-premises and VNet-to-VNet connectivity](https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-highlyavailable#active-active-vpn-gateways)
