### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by segoja7** [aws-samples/terraform-aws-windows-workloads-on-aws#6]
Is your request related to a new offering from AWS?

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md).

  - No 🛑: please wait to file a request until the functionality is available in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I am testing an automatization for workloads in windows, when the module "aws-samples/windows-workloads-on-aws/aws//modules/managed-ad" create a secret by first time work, but when you recreate this secret terraform show this error.

Error: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
    status code: 400, request id: e4f8cc85-29a4-46ff-911d-c5115716adc5

## Describe the solution you'd like.
You need only add recovery_window_in_days as variable.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret#recovery_window_in_days

## Describe alternatives you've considered.
By the moment is possible to make more testing changing the name of the variable: ds_managed_ad_directory_name this solve the error, but in other execution is necessary changing again the name.

**Comment by marciogmorales** [comment]
Hello,
When re-running Terraform, did you check if the Directory Service was fully deleted? It takes more than 30min to be fully deleted.

**Comment by segoja7** [comment]
Hello @marciogmorales 
No, I didn't check, but if you can add [recovery_window_in_days](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret#recovery_window_in_days) this alllow us more control over this secret.

**Comment by marciogmorales** [comment]
Fixed, thank you for the feedback.
