### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by boyobejamin** [aws-samples/terraform-aws-windows-workloads-on-aws#8]
## Description

The explicit use of a profile should be removed in `main.tf` [here](https://github.com/aws-samples/terraform-aws-windows-workloads-on-aws/blob/main/modules/managed-ad/main.tf#L18) as only users with this profile can execute the sample code.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by marciogmorales** [comment]
Fixed. 
It was left by mistake.
